export const API = '/api'
export const USER = '/user'
export const SAVE = '/save'
export const QUESTION = '/question'
export const TEST = '/test'
export const VIDEO = '/video'
export const CANDIDATE_TYPE = '/candidatetype'
export const KNOWLEDGE_TYPE = '/knowledgetype'
